// Package srs generates sing-box binary rule-sets containing IP CIDRs.
package srs

import (
	"bufio"
	"compress/zlib"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"net/netip"
	"os"
	"sort"
	"strings"
)

var magic = [3]byte{'S', 'R', 'S'}

const (
	formatVersion   = uint8(1)
	ruleTypeDefault = uint8(0)
	ruleItemIPCIDR  = uint8(6)
	ruleItemFinal   = uint8(0xff)
	ipSetVersion    = uint8(1)
)

type ipRange struct {
	from netip.Addr
	to   netip.Addr
}

// RuleSet is the IP matcher recovered from an SRS file generated by this package.
type RuleSet struct {
	ranges []ipRange
}

// Contains reports whether address is included in the rule-set.
func (ruleSet *RuleSet) Contains(address netip.Addr) bool {
	address = address.Unmap()
	index := sort.Search(len(ruleSet.ranges), func(index int) bool {
		return compareAddress(ruleSet.ranges[index].to, address) >= 0
	})
	return index < len(ruleSet.ranges) && compareAddress(ruleSet.ranges[index].from, address) <= 0
}

// Generate creates a sing-box SRS v1 binary rule-set from a CIDR list.
// Version 1 is sufficient for IP rules and works with sing-box 1.8.0 and later.
func Generate(source, destination string) error {
	ranges, err := readCIDRs(source)
	if err != nil {
		return err
	}
	if len(ranges) == 0 {
		return errors.New("CIDR list contains no entries")
	}

	output, err := os.Create(destination)
	if err != nil {
		return fmt.Errorf("create SRS: %w", err)
	}
	if err := write(output, ranges); err != nil {
		output.Close()
		return fmt.Errorf("write SRS: %w", err)
	}
	if err := output.Close(); err != nil {
		return fmt.Errorf("close SRS: %w", err)
	}
	return nil
}

func readCIDRs(path string) ([]ipRange, error) {
	input, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open CIDR list: %w", err)
	}
	defer input.Close()

	var ranges []ipRange
	scanner := bufio.NewScanner(input)
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		fields := strings.Fields(scanner.Text())
		if len(fields) == 0 || strings.HasPrefix(fields[0], "#") {
			continue
		}
		prefix, err := netip.ParsePrefix(fields[0])
		if err != nil {
			return nil, fmt.Errorf("parse CIDR list line %d: %w", lineNumber, err)
		}
		prefix = prefix.Masked()
		ranges = append(ranges, ipRange{from: prefix.Addr().Unmap(), to: lastAddress(prefix)})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read CIDR list: %w", err)
	}
	return mergeRanges(ranges), nil
}

func lastAddress(prefix netip.Prefix) netip.Addr {
	address := prefix.Masked().Addr().Unmap()
	bits := address.BitLen()
	if address.Is4() {
		value := address.As4()
		for bit := prefix.Bits(); bit < bits; bit++ {
			value[bit/8] |= byte(1) << uint(7-bit%8)
		}
		return netip.AddrFrom4(value)
	}
	value := address.As16()
	for bit := prefix.Bits(); bit < bits; bit++ {
		value[bit/8] |= byte(1) << uint(7-bit%8)
	}
	return netip.AddrFrom16(value)
}

func mergeRanges(ranges []ipRange) []ipRange {
	sort.Slice(ranges, func(left, right int) bool {
		return compareAddress(ranges[left].from, ranges[right].from) < 0
	})
	merged := make([]ipRange, 0, len(ranges))
	for _, current := range ranges {
		if len(merged) == 0 {
			merged = append(merged, current)
			continue
		}
		last := &merged[len(merged)-1]
		next := last.to.Next()
		if sameAddressFamily(last.to, current.from) &&
			(compareAddress(current.from, last.to) <= 0 || next.IsValid() && current.from == next) {
			if compareAddress(current.to, last.to) > 0 {
				last.to = current.to
			}
			continue
		}
		merged = append(merged, current)
	}
	return merged
}

func compareAddress(left, right netip.Addr) int {
	if left.Is4() != right.Is4() {
		if left.Is4() {
			return -1
		}
		return 1
	}
	return left.Compare(right)
}

func sameAddressFamily(left, right netip.Addr) bool {
	return left.Is4() == right.Is4()
}

func write(writer io.Writer, ranges []ipRange) error {
	if _, err := writer.Write(magic[:]); err != nil {
		return err
	}
	if err := binary.Write(writer, binary.BigEndian, formatVersion); err != nil {
		return err
	}
	compressed, err := zlib.NewWriterLevel(writer, zlib.BestCompression)
	if err != nil {
		return err
	}
	buffered := bufio.NewWriter(compressed)
	if err := writeUvarint(buffered, 1); err != nil { // one default rule
		return err
	}
	if err := buffered.WriteByte(ruleTypeDefault); err != nil {
		return err
	}
	if err := buffered.WriteByte(ruleItemIPCIDR); err != nil {
		return err
	}
	if err := writeIPSet(buffered, ranges); err != nil {
		return err
	}
	if err := buffered.WriteByte(ruleItemFinal); err != nil {
		return err
	}
	if err := buffered.WriteByte(0); err != nil { // invert=false
		return err
	}
	if err := buffered.Flush(); err != nil {
		return err
	}
	return compressed.Close()
}

func writeIPSet(writer *bufio.Writer, ranges []ipRange) error {
	if err := writer.WriteByte(ipSetVersion); err != nil {
		return err
	}
	if err := binary.Write(writer, binary.BigEndian, uint64(len(ranges))); err != nil {
		return err
	}
	for _, addressRange := range ranges {
		if err := writeAddress(writer, addressRange.from); err != nil {
			return err
		}
		if err := writeAddress(writer, addressRange.to); err != nil {
			return err
		}
	}
	return nil
}

func writeAddress(writer *bufio.Writer, address netip.Addr) error {
	value := address.AsSlice()
	if err := writeUvarint(writer, uint64(len(value))); err != nil {
		return err
	}
	_, err := writer.Write(value)
	return err
}

func writeUvarint(writer io.ByteWriter, value uint64) error {
	var buffer [binary.MaxVarintLen64]byte
	length := binary.PutUvarint(buffer[:], value)
	for _, item := range buffer[:length] {
		if err := writer.WriteByte(item); err != nil {
			return err
		}
	}
	return nil
}

// Read reads the IP matcher from a sing-box SRS file containing one IP rule.
func Read(reader io.Reader) (*RuleSet, error) {
	var fileMagic [3]byte
	if _, err := io.ReadFull(reader, fileMagic[:]); err != nil {
		return nil, err
	}
	if fileMagic != magic {
		return nil, errors.New("invalid sing-box rule-set file")
	}
	version, err := readByte(reader)
	if err != nil {
		return nil, err
	}
	if version != formatVersion {
		return nil, fmt.Errorf("unsupported SRS version %d", version)
	}
	compressed, err := zlib.NewReader(reader)
	if err != nil {
		return nil, err
	}
	defer compressed.Close()
	buffered := bufio.NewReader(compressed)
	ruleCount, err := binary.ReadUvarint(buffered)
	if err != nil {
		return nil, err
	}
	if ruleCount != 1 {
		return nil, fmt.Errorf("unsupported SRS rule count %d", ruleCount)
	}
	ruleType, err := buffered.ReadByte()
	if err != nil {
		return nil, err
	}
	if ruleType != ruleTypeDefault {
		return nil, fmt.Errorf("unsupported SRS rule type %d", ruleType)
	}
	itemType, err := buffered.ReadByte()
	if err != nil {
		return nil, err
	}
	if itemType != ruleItemIPCIDR {
		return nil, fmt.Errorf("unsupported SRS rule item %d", itemType)
	}
	ranges, err := readIPSet(buffered)
	if err != nil {
		return nil, err
	}
	final, err := buffered.ReadByte()
	if err != nil {
		return nil, err
	}
	if final != ruleItemFinal {
		return nil, errors.New("SRS rule is missing final item")
	}
	invert, err := buffered.ReadByte()
	if err != nil {
		return nil, err
	}
	if invert != 0 {
		return nil, errors.New("inverted SRS rules are unsupported")
	}
	return &RuleSet{ranges: ranges}, nil
}

func readIPSet(reader *bufio.Reader) ([]ipRange, error) {
	version, err := reader.ReadByte()
	if err != nil {
		return nil, err
	}
	if version != ipSetVersion {
		return nil, fmt.Errorf("unsupported SRS IP set version %d", version)
	}
	var count uint64
	if err := binary.Read(reader, binary.BigEndian, &count); err != nil {
		return nil, err
	}
	if count > uint64(^uint(0)>>1) {
		return nil, errors.New("SRS IP range count is too large")
	}
	ranges := make([]ipRange, int(count))
	for index := range ranges {
		from, err := readAddress(reader)
		if err != nil {
			return nil, err
		}
		to, err := readAddress(reader)
		if err != nil {
			return nil, err
		}
		if !sameAddressFamily(from, to) || compareAddress(from, to) > 0 {
			return nil, errors.New("invalid SRS IP range")
		}
		ranges[index] = ipRange{from: from, to: to}
	}
	return ranges, nil
}

func readAddress(reader *bufio.Reader) (netip.Addr, error) {
	length, err := binary.ReadUvarint(reader)
	if err != nil {
		return netip.Addr{}, err
	}
	if length != 4 && length != 16 {
		return netip.Addr{}, fmt.Errorf("invalid SRS address length %d", length)
	}
	value := make([]byte, int(length))
	if _, err := io.ReadFull(reader, value); err != nil {
		return netip.Addr{}, err
	}
	address, ok := netip.AddrFromSlice(value)
	if !ok {
		return netip.Addr{}, errors.New("invalid SRS address")
	}
	return address.Unmap(), nil
}

func readByte(reader io.Reader) (byte, error) {
	var value [1]byte
	_, err := io.ReadFull(reader, value[:])
	return value[0], err
}
